import type { Metadata } from 'next'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter'
import { Roboto } from 'next/font/google'
import { ThemeProvider } from '@mui/material/styles'
import { QueryProvider } from '@/components/atoms/ProviderWrapper'
import theme from '@/components/atoms/Theme'
import AdminLayout from '@/components/templates/AdminLayout'

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayoutAdmin({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <AppRouterCacheProvider>
      <ThemeProvider theme={theme}>
        <QueryProvider>
          <AdminLayout>{children}</AdminLayout>
        </QueryProvider>
      </ThemeProvider>
    </AppRouterCacheProvider>
  )
}
