import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import HideSidebarButton from '@/components/hideSidebar'
import RouteLink from '@/components/RouteLink'

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayoutAdmin({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <div
          id="sidebar_nav"
          className="grid grid-cols-[200px_1fr] duration-300 ease-in-out"
        >
          <div className="h-14 w-auto  border-b-2 border-gray-200 ">
            <nav className="p-3">
              <div>Logo</div>
            </nav>
          </div>
          <div className="h-14 w-auto border-l-2 border-b-2 border-gray-200">
            <HideSidebarButton />
          </div>
        </div>
        <div
          id="sidebar_menu"
          className="grid grid-cols-[200px_1fr] h-[calc(100vh-56px)] duration-300 ease-in-out"
        >
          <div className="w-auto ">
            <ul className="p-3 text-nowrap ">
              <li className="p-3 w-full">
                <RouteLink href="/menu1" active className="p-3 w-full">
                  Menu 1
                </RouteLink>
                {/* <RouteLink href="/menu2">Menu 2</RouteLink> */}
              </li>
              <li className="p-3">
                <RouteLink href="/menu1" active className="p-3 w-full">
                  Menu 1
                </RouteLink>
                {/* <RouteLink href="/menu2">Menu 2</RouteLink> */}
              </li>
            </ul>
          </div>
          <div className="h-full w-full p-3 bg-white border-l-2 border-gray-200">
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
